spring:
  application:
    name: java-reactive-messaging
  profiles:
    active: dev

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ecommerce
    username: user
    password: password

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/ecommerce
    user: user
    password: password
    locations: classpath:db/migration

  cassandra:
    contact-points: localhost:9042
    local-datacenter: datacenter1
    keyspace-name: ecommerce
    schema-action: create_if_not_exists

  data:
    redis:
      host: localhost
      port: 6379

  main:
    web-application-type: reactive
